com:
  stonksmmo:
    StonksMMOUserBackend:
      jwtSecret: AZGGHKDARTFHAWUID1244SDAFD243T5WQRSNA1294817lMagbda

stonksJwtExpirationTime:
  jwtExpirationMs: 840000000






spring:
  cloud:
    discovery:
      enabled: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
      url: jdbc://mysql://b3595316435fef:55db0038@us-cdbr-east-03.cleardb.com/heroku_9cc9073b421fcb2?reconnect=true
      username: b3595316435fef
      password: 55db0038
      driver-class-name: com.mysql.jdbc.Driver






debug: true


eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8090/eureka
      server.port: 8079
    fetch-registry: false
zuul:
  routes:
    service_1:
      path: https://stonkszuuluserbackend.herokuapp.com/
  prefix: /api


